version: '3.9'

services:
    ### Reverse-Proxy (traefik) ###
    proxy:
        image: traefik:2.5.3
        command: --api.insecure=true --providers.docker
        ports:
            # The HTTP port
            - "80:80"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
    ### APP (php-fpm + nginx) ###
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
            target: dev
        volumes:
            # used delegated mode here on docker for mac for faster disk I/O
            - .:/var/www/html:delegated
        labels:
            - traefik.http.routers.app.rule=Host(`${DOCKER_SERVER_NAME:-gambling.localhost}`)
            - traefik.http.services.app.loadbalancer.server.port=80
        entrypoint: /usr/local/bin/docker-php-entrypoint-dev
        command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf" ]
